sudo: required
language: python
python:
- '3.4'
before_install:
- sudo add-apt-repository ppa:koffeinflummi/armake -y
- sudo apt-get update -qq
- sudo apt-get install armake -y
install: true
script:
- make
- python3 tools/sqf_validator.py
- python3 tools/config_style_checker.py
notifications:
  email:
    on_success: never
    on_failure: change
