version: 2
jobs:
  build:
    docker:
      - image: acemod/armake
    steps:
      - checkout
      - run:
          name: Validate SQF And Config style
          command: python tools/sqf_validator.py && python tools/config_style_checker.py
      - run:
          name: Version
          command: armake --version
      - run:
          name: Build
          command: |
            make -j 4
      - deploy:
          name: Update documentation and translation statistics
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] && [ "${CIRCLE_PROJECT_USERNAME}" == "CBATeam" ]; then
              echo pip install pygithub pygithub3  # To be moved from Travis
              echo python3 tools/deploy.py  # To be moved from Travis
            else
              echo "Skipping, not on CBATeam/CBA_A3 master branch..."
            fi
